exit 1

diff --git a/.github/workflows/code-formatting.yml b/.github/workflows/code-formatting.yml
--- a/.github/workflows/code-formatting.yml
+++ b/.github/workflows/code-formatting.yml
@@ -17,30 +17,30 @@ jobs:
       run: |
         sudo apt-get update
         sudo apt-get install clang-format -y
-        clang-format --version  # Check the version installed for debugging
-    - name: Run clang-format and check for unformatted code
+        clang-format --version
+    - name: Run clang-format to check for unformatted code
       id: clang_format_check
       run: |
         find . -iname '*.hpp' -o -iname '*.cpp' | xargs clang-format --dry-run --Werror --style=Google
-      continue-on-error: true # Continue the workflow even if there are formatting issues
+      continue-on-error: true  # Allow other steps to run even if this fails
 
   warn-unformatted:
     runs-on: ubuntu-latest
     if: github.event_name == 'push' && github.ref != 'refs/heads/main'
     needs: format-check
     steps:
-    - name: Warn the user about unformatted code
+    - name: Warn user about unformatted code
       if: steps.clang_format_check.outcome == 'failure'
       run: |
-        echo "Warning: Code is not formatted according to clang-format. Please consider formatting the code."
+        echo "Warning: Your code is not formatted according to clang-format. Please format the code."
 
   block-unformatted:
     runs-on: ubuntu-latest
     if: github.event_name == 'pull_request' && github.base_ref == 'main'
     needs: format-check
     steps:
-    - name: Fail pull request on unformatted code
+    - name: Fail PR on unformatted code
       if: steps.clang_format_check.outcome == 'failure'
       run: |
-        echo "Error: Code is not formatted according to clang-format. The pull request cannot be merged into the main branch."
-        exit 1  # Explicitly fail the job if the code is not formatted
+        echo "Error: Your code is not formatted according to clang-format. The pull request cannot be merged into the main branch."
+        exit 1  # Explicitly fail the PR if the code is unformatted
